CREATE TABLE "GCG_6238_MAINT" (
 "BIN" CHAR(6),
 "LOCATION" CHAR(2),
 "COUNT_FLAG" CHAR(1),
 "DATE_LAST_COUNT" DATE,
 "RUN_ID" CHAR(9),
 "USER_ID" CHAR(8),
 "START_TIME" CHAR(5),
 "STOP_TIME" CHAR(5),
 "PART" CHAR(20) );
CREATE UNIQUE INDEX "BIN_LOC0" USING 0 IN DICTIONARY  ON "GCG_6238_MAINT" ( "BIN", "LOCATION" );